-- Mia's Scent database schema.
-- Run this once in Supabase: Dashboard → SQL Editor → New query → paste → Run.

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Random ID generated by the checkout page; stops double-clicks creating two orders.
  client_request_id uuid not null,
  customer_name text not null,
  phone text not null,
  address text not null,
  email text not null,
  total integer not null check (total >= 0), -- whole naira
  email_status text not null default 'pending'
    check (email_status in ('pending', 'sent', 'failed')),
  created_at timestamptz not null default now(),
  unique (user_id, client_request_id)
);

create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id text not null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total integer not null check (line_total >= 0)
);

create index if not exists orders_user_id_created_at_idx
  on public.orders (user_id, created_at desc);
create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

-- Row Level Security: customers can only READ their own orders.
-- There are no insert/update/delete policies, so only the server
-- (using the service-role key, after checking the user and prices) can write.
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Customers can view their own orders" on public.orders;
create policy "Customers can view their own orders"
  on public.orders for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Customers can view items in their own orders" on public.order_items;
create policy "Customers can view items in their own orders"
  on public.order_items for select
  to authenticated
  using (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
        and orders.user_id = (select auth.uid())
    )
  );
